version: "3.8"

services:
  flask_app:
    build: 
      context: .
    container_name: rate-limiter-demo
    ports:
      - "5001:5001"
    depends_on:
      - redis
    networks:
      - flask_network

  redis:
    image: "redis:alpine"
    container_name: redis
    ports:
      - "6379"
    networks:
      - flask_network

networks:
  flask_network:
    driver: bridge
